#pragma once

/* Generated by asset converters. */

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#elif defined(LV_LVGL_H_INCLUDE_SYSTEM)
#include <lvgl.h>
#else
#include "lvgl/lvgl.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Images */
LV_IMAGE_DECLARE(image_icon_basic_wave);
LV_IMAGE_DECLARE(image_icon_delete);
LV_IMAGE_DECLARE(image_icon_line_wave);
LV_IMAGE_DECLARE(image_icon_list);
LV_IMAGE_DECLARE(image_icon_nav_back);
LV_IMAGE_DECLARE(image_icon_nav_down);
LV_IMAGE_DECLARE(image_icon_nav_up);
LV_IMAGE_DECLARE(image_icon_pause);
LV_IMAGE_DECLARE(image_icon_play);
LV_IMAGE_DECLARE(image_icon_prism_wave);
LV_IMAGE_DECLARE(image_icon_record);
LV_IMAGE_DECLARE(image_icon_spectrum_wave);
LV_IMAGE_DECLARE(image_icon_stop);
LV_IMAGE_DECLARE(image_key_indicators);

/* Fonts */
LV_FONT_DECLARE(font_chivo_mono_medium_12);
LV_FONT_DECLARE(font_chivo_medium_14);

#ifdef __cplusplus
}
#endif
