#pragma once

/* Generated by projects/Recorder/main/src/assets/convert.py. */

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#elif defined(LV_LVGL_H_INCLUDE_SYSTEM)
#include <lvgl.h>
#else
#include "lvgl/lvgl.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Images */
LV_IMAGE_DECLARE(icon_list);
LV_IMAGE_DECLARE(icon_pause);
LV_IMAGE_DECLARE(icon_record);
LV_IMAGE_DECLARE(icon_stop);
LV_IMAGE_DECLARE(key_indicators);

#ifdef __cplusplus
}
#endif
