#pragma once

/* Generated by Recorder asset converters. */

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#elif defined(LV_LVGL_H_INCLUDE_SYSTEM)
#include <lvgl.h>
#else
#include "lvgl/lvgl.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Images */
LV_IMAGE_DECLARE(image_icon_list);
LV_IMAGE_DECLARE(image_icon_pause);
LV_IMAGE_DECLARE(image_icon_record);
LV_IMAGE_DECLARE(image_icon_stop);
LV_IMAGE_DECLARE(image_key_indicators);

/* Fonts */
LV_FONT_DECLARE(font_chivo_mono_medium_12);

#ifdef __cplusplus
}
#endif
