#!/usr/bin/env python3

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
import tempfile
from pathlib import Path
from typing import Iterable


ASSETS_DIR = Path(__file__).resolve().parent
IMAGES_DIR = ASSETS_DIR / "images"
RES_C_DIR = ASSETS_DIR / "res_c"
ASSETS_H = ASSETS_DIR / "assets.h"
GENERATED_MARKER = "/* Generated by projects/Recorder/main/src/assets/convert.py. */"

IMAGE_FORMAT_BY_EXT = {
    ".png": "RGB565A8",
    ".jpg": "RGB565",
    ".jpeg": "RGB565",
}


def repo_root() -> Path:
    for parent in [ASSETS_DIR, *ASSETS_DIR.parents]:
        if (parent / "SDK" / "github_source" / "lvgl" / "lvgl_9_5" / "lvgl" / "scripts" / "LVGLImage.py").exists():
            return parent
    raise FileNotFoundError(
        "Cannot find LVGLImage.py under SDK/github_source/lvgl/lvgl_9_5/lvgl/scripts")


def lvgl_image_script() -> Path:
    return repo_root() / "SDK" / "github_source" / "lvgl" / "lvgl_9_5" / "lvgl" / "scripts" / "LVGLImage.py"


def load_lvgl_image_module():
    script = lvgl_image_script()
    spec = importlib.util.spec_from_file_location("LVGLImage", script)
    if spec is None or spec.loader is None:
        raise ImportError(f"Failed to load {script}")

    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except ImportError as exc:
        raise ImportError(
            f"{exc}\n"
            "Install LVGL image converter dependencies first, for example:\n"
            "  pip3 install pypng lz4\n"
            "JPEG input also requires Pillow:\n"
            "  pip3 install Pillow"
        ) from exc
    return module


def sanitize_symbol(path: Path) -> str:
    symbol = re.sub(r"[^0-9A-Za-z_]", "_", path.stem)
    symbol = re.sub(r"_+", "_", symbol).strip("_")
    if not symbol:
        symbol = "image"
    if symbol[0].isdigit():
        symbol = f"img_{symbol}"
    return symbol


def iter_images(images_dir: Path) -> list[Path]:
    if not images_dir.exists():
        return []

    files = [
        path
        for path in images_dir.rglob("*")
        if path.is_file() and path.suffix.lower() in IMAGE_FORMAT_BY_EXT and not path.name.startswith(".")
    ]
    return sorted(files, key=lambda item: item.relative_to(images_dir).as_posix())


def ensure_unique_symbols(images: Iterable[Path]) -> dict[Path, str]:
    symbols: dict[Path, str] = {}
    used: dict[str, Path] = {}
    for image in images:
        symbol = sanitize_symbol(image)
        if symbol in used:
            raise ValueError(
                f"Image symbol collision: {used[symbol]} and {image} both become {symbol}")
        used[symbol] = image
        symbols[image] = symbol
    return symbols


def temporary_png_from_jpeg(path: Path, tmp_dir: Path) -> Path:
    try:
        from PIL import Image
    except ImportError as exc:
        raise ImportError(
            f"JPEG input requires Pillow, but it is not installed. Install it with:\n"
            f"  pip3 install Pillow\n"
            f"Failed file: {path}"
        ) from exc

    out = tmp_dir / f"{path.stem}.png"
    with Image.open(path) as image:
        image.convert("RGBA").save(out)
    return out


def prepend_generated_marker(path: Path) -> None:
    content = path.read_text()
    if content.startswith(GENERATED_MARKER):
        return
    path.write_text(f"{GENERATED_MARKER}\n{content}")


def replace_if_changed(source: Path, target: Path) -> bool:
    new_content = source.read_text()
    if target.exists() and target.read_text() == new_content:
        return False
    target.write_text(new_content)
    return True


def display_path(path: Path, base: Path = ASSETS_DIR) -> str:
    try:
        return path.relative_to(base).as_posix()
    except ValueError:
        return path.as_posix()


def remove_stale_generated_files(expected_outputs: set[Path]) -> None:
    for path in RES_C_DIR.glob("*.c"):
        if path in expected_outputs:
            continue
        try:
            first_line = path.read_text(errors="ignore").splitlines()[0]
        except IndexError:
            first_line = ""
        if first_line == GENERATED_MARKER:
            path.unlink()
            print(f"removed stale {display_path(path)}")


def convert_image(module, source: Path, symbol: str, color_format: str,
                  tmp_dir: Path) -> tuple[Path, bool]:
    input_path = source
    if source.suffix.lower() in (".jpg", ".jpeg"):
        input_path = temporary_png_from_jpeg(source, tmp_dir)

    RES_C_DIR.mkdir(parents=True, exist_ok=True)
    out_c = RES_C_DIR / f"{symbol}.c"
    tmp_c = tmp_dir / f"{symbol}.c"
    image = module.LVGLImage().from_png(
        str(input_path), module.ColorFormat[color_format])
    image.adjust_stride(align=1)
    image.to_c_array(str(tmp_c), outputname=symbol)
    prepend_generated_marker(tmp_c)
    changed = replace_if_changed(tmp_c, out_c)
    return out_c, changed


def write_assets_header(symbols: list[str]) -> bool:
    lines = [
        "#pragma once",
        "",
        GENERATED_MARKER,
        "",
        "#if defined(LV_LVGL_H_INCLUDE_SIMPLE)",
        '#include "lvgl.h"',
        "#elif defined(LV_LVGL_H_INCLUDE_SYSTEM)",
        "#include <lvgl.h>",
        "#else",
        '#include "lvgl/lvgl.h"',
        "#endif",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]

    if symbols:
        lines.append("/* Images */")
        for symbol in symbols:
            lines.append(f"LV_IMAGE_DECLARE({symbol});")
    else:
        lines.append("/* Images: none */")

    lines += [
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ]
    content = "\n".join(lines)
    if ASSETS_H.exists() and ASSETS_H.read_text() == content:
        return False
    ASSETS_H.write_text(content)
    return True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert Recorder image assets to LVGL C arrays.")
    parser.add_argument("--images-dir", type=Path, default=IMAGES_DIR,
                        help="Input image directory.")
    parser.add_argument("--output-dir", type=Path, default=RES_C_DIR,
                        help="Generated C output directory.")
    parser.add_argument(
        "--no-clean",
        action="store_true",
        help="Do not remove previously generated .c files that no longer have a raw image.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    images_dir = args.images_dir.resolve()
    global RES_C_DIR
    RES_C_DIR = args.output_dir.resolve()

    images = iter_images(images_dir)
    symbols_by_image = ensure_unique_symbols(images)
    module = load_lvgl_image_module()

    expected_outputs: set[Path] = set()
    with tempfile.TemporaryDirectory(prefix="recorder-assets-") as tmp:
        tmp_dir = Path(tmp)
        for image in images:
            symbol = symbols_by_image[image]
            color_format = IMAGE_FORMAT_BY_EXT[image.suffix.lower()]
            out_c, changed = convert_image(module, image, symbol, color_format, tmp_dir)
            expected_outputs.add(out_c)
            status = "updated" if changed else "unchanged"
            print(
                f"{display_path(image, images_dir)} -> {display_path(out_c)} ({color_format}, {symbol}, {status})")

    if not args.no_clean:
        remove_stale_generated_files(expected_outputs)

    symbols = [symbols_by_image[image] for image in images]
    header_changed = write_assets_header(symbols)
    status = "updated" if header_changed else "unchanged"
    print(f"{status} {display_path(ASSETS_H, repo_root())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
