import os
from pathlib import Path

Import('env')
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())

SRCS = append_srcs_dir([ADir('src')])
INCLUDE = [ADir('.'), ADir('src')]
PRIVATE_INCLUDE = []
REQUIREMENTS = ['cp0_lvgl', 'lvgl_component', 'pthread']
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = []
DEFINITIONS_PRIVATE = []
LDFLAGS = []
LINK_SEARCH_PATH = []
STATIC_FILES = []

PROJECT_ROOT = Path(env['PROJECT_PATH'])
DEPENDENCIES = PROJECT_ROOT / 'dependencies'
SPDLOG = DEPENDENCIES / 'spdlog'
SMOOTH_UI_TOOLKIT = DEPENDENCIES / 'smooth_ui_toolkit'

if SPDLOG.exists():
    INCLUDE += [str(SPDLOG / 'include')]

if SMOOTH_UI_TOOLKIT.exists():
    INCLUDE += [
        str(SMOOTH_UI_TOOLKIT / 'src'),
        str(SMOOTH_UI_TOOLKIT / 'src' / 'lvgl'),
    ]
    SRCS += append_srcs_dir([str(SMOOTH_UI_TOOLKIT / 'src')])

lvgl_component = list(
    filter(lambda x: x['target'] == 'lvgl_component', env['COMPONENTS']))[0]
toolchain_sysroot = os.environ.get('CONFIG_TOOLCHAIN_SYSROOT', '') or '/'

if 'CONFIG_V9_5_LV_USE_SDL' in os.environ:
    lvgl_component['REQUIREMENTS'] += ['SDL2']
    lvgl_component['INCLUDE'] += ['/usr/include/SDL2']
    lvgl_component['DEFINITIONS'] += ['-D_REENTRANT']

if 'CONFIG_V9_5_LV_USE_FREETYPE' in os.environ:
    lvgl_component['REQUIREMENTS'] += ['freetype']
    lvgl_component['INCLUDE'] += [
        f"{os.path.join(toolchain_sysroot, 'usr', 'include', 'freetype2')}",
        f"{os.path.join(toolchain_sysroot, 'usr', 'include', 'libpng16')}",
    ]

for src in lvgl_component['SRCS']:
    if 'lv_sdl_keyboard.c' in str(src):
        lvgl_component['SRCS'].remove(src)

env['COMPONENTS'].append({
    'target': env['PROJECT_NAME'],
    'SRCS': SRCS,
    'INCLUDE': INCLUDE,
    'PRIVATE_INCLUDE': PRIVATE_INCLUDE,
    'REQUIREMENTS': REQUIREMENTS,
    'STATIC_LIB': STATIC_LIB,
    'DYNAMIC_LIB': DYNAMIC_LIB,
    'DEFINITIONS': DEFINITIONS,
    'DEFINITIONS_PRIVATE': DEFINITIONS_PRIVATE,
    'LDFLAGS': LDFLAGS,
    'LINK_SEARCH_PATH': LINK_SEARCH_PATH,
    'STATIC_FILES': STATIC_FILES,
    'REGISTER': 'project',
})
