import os
from pathlib import Path

Import('env')
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())

SRCS = append_srcs_dir([ADir('src')])
INCLUDE = [ADir('.'), ADir('src')]
PRIVATE_INCLUDE = []
REQUIREMENTS = ['cp0_lvgl', 'lvgl_component', 'pthread']
STATIC_LIB = []
DYNAMIC_LIB = []
DEFINITIONS = ['-std=c++17']
DEFINITIONS_PRIVATE = []
LDFLAGS = []
LINK_SEARCH_PATH = []
STATIC_FILES = []

PROJECT_ROOT = Path(env['PROJECT_PATH'])
DEPENDENCIES = PROJECT_ROOT / 'dependencies'
SPDLOG = DEPENDENCIES / 'spdlog'
SMOOTH_UI_TOOLKIT = DEPENDENCIES / 'smooth_ui_toolkit'

if SPDLOG.exists():
    INCLUDE += [str(SPDLOG / 'include')]

if SMOOTH_UI_TOOLKIT.exists():
    INCLUDE += [
        str(SMOOTH_UI_TOOLKIT / 'src'),
        str(SMOOTH_UI_TOOLKIT / 'src' / 'lvgl'),
    ]
    SRCS += append_srcs_dir([str(SMOOTH_UI_TOOLKIT / 'src')])

lvgl_component = list(
    filter(lambda x: x['target'] == 'lvgl_component', env['COMPONENTS']))[0]

if 'CONFIG_V9_5_LV_USE_SDL' in os.environ:
    import platform
    DEFINITIONS += ['-DCOMPASS_USE_MOCK_IMU=1']
    lvgl_component['REQUIREMENTS'] += ['SDL2']
    if platform.system() == 'Darwin':
        sdl2_cflags = pkg_config_cflags('sdl2')
        for flag in sdl2_cflags:
            if flag.startswith('-I'):
                sdl2_dir = flag[2:]
                lvgl_component['INCLUDE'] += [
                    os.path.dirname(sdl2_dir), sdl2_dir]
        for flag in pkg_config_ldflags('sdl2'):
            if flag.startswith('-L'):
                lvgl_component['LINK_SEARCH_PATH'] += [flag[2:]]
        if not sdl2_cflags:
            lvgl_component['INCLUDE'] += ['/opt/homebrew/include',
                                          '/opt/homebrew/include/SDL2']
            lvgl_component['LINK_SEARCH_PATH'] += ['/opt/homebrew/lib']
    else:
        lvgl_component['INCLUDE'] += ['/usr/include/SDL2']
    lvgl_component['DEFINITIONS'] += ['-D_REENTRANT']
else:
    DEFINITIONS += ['-DCOMPASS_USE_IIO_IMU=1']

for src in lvgl_component['SRCS']:
    if 'lv_sdl_keyboard.c' in str(src):
        lvgl_component['SRCS'].remove(src)

env['COMPONENTS'].append({
    'target': 'M5CardputerZero-Compass',
    'SRCS': SRCS,
    'INCLUDE': INCLUDE,
    'PRIVATE_INCLUDE': PRIVATE_INCLUDE,
    'REQUIREMENTS': REQUIREMENTS,
    'STATIC_LIB': STATIC_LIB,
    'DYNAMIC_LIB': DYNAMIC_LIB,
    'DEFINITIONS': DEFINITIONS,
    'DEFINITIONS_PRIVATE': DEFINITIONS_PRIVATE,
    'LDFLAGS': LDFLAGS,
    'LINK_SEARCH_PATH': LINK_SEARCH_PATH,
    'STATIC_FILES': STATIC_FILES,
    'REGISTER': 'project',
})
