#pragma once

/* Generated by asset converters. */

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#elif defined(LV_LVGL_H_INCLUDE_SYSTEM)
#include <lvgl.h>
#else
#include "lvgl/lvgl.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Images */
LV_IMAGE_DECLARE(image_calibration_guesture);
LV_IMAGE_DECLARE(image_compass_dial);
LV_IMAGE_DECLARE(image_icon_back);
LV_IMAGE_DECLARE(image_icon_calibration);
LV_IMAGE_DECLARE(image_icon_more);
LV_IMAGE_DECLARE(image_magic);
LV_IMAGE_DECLARE(image_magic_fire);

/* Fonts */
LV_FONT_DECLARE(font_chivo_mono_medium_12);
LV_FONT_DECLARE(font_chivo_medium_14);

#ifdef __cplusplus
}
#endif
