#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

import convert_images


ASSETS_DIR = Path(__file__).resolve().parent
FONTS_DIR = ASSETS_DIR / "fonts"
IMAGES_DIR = ASSETS_DIR / "images"
RES_C_DIR = ASSETS_DIR / "res_c"
FONT_MARKER = "/* Generated by assets/convert_fonts.py. */"


def find_lv_font_conv() -> str:
    env_path = os.environ.get("LV_FONT_CONV")
    if env_path:
        return env_path

    path = shutil.which("lv_font_conv")
    if path:
        return path

    raise FileNotFoundError(
        "Cannot find lv_font_conv. Install it manually and make it available in PATH, "
        "or set LV_FONT_CONV to the executable path.")


def load_config(path: Path) -> list[dict]:
    content = path.read_text().strip()
    if not content:
        return []

    config = json.loads(content)
    if isinstance(config, list):
        return config
    if isinstance(config, dict):
        return config.get("targets", [])
    raise ValueError(f"Font config must be an object or list: {path}")


def normalize_list(value) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item) for item in value]
    return [str(value)]


def font_targets(fonts_dir: Path) -> list[dict]:
    targets: list[dict] = []
    used: dict[str, Path] = {}
    if not fonts_dir.exists():
        return targets

    for config_path in sorted(fonts_dir.rglob("font_config.json")):
        for item in load_config(config_path):
            if not isinstance(item, dict):
                raise ValueError(
                    f"Font target must be an object: {config_path}")

            name = item.get("name") or item.get("target") or item.get("output")
            source_name = item.get("source") or item.get(
                "src") or item.get("file")
            if not name:
                raise ValueError(
                    f"Font target misses name/target/output: {config_path}")
            if not source_name:
                raise ValueError(
                    f"Font target misses source/src/file: {config_path}")

            symbol = convert_images.sanitize_symbol(str(name))
            if symbol in used:
                raise ValueError(
                    f"Font symbol collision: {used[symbol]} and {config_path} both become {symbol}")
            used[symbol] = config_path

            source = (config_path.parent / str(source_name)).resolve()
            if not source.exists():
                raise FileNotFoundError(f"Font file does not exist: {source}")

            target = dict(item)
            target["config"] = config_path
            target["source_path"] = source
            target["symbol"] = symbol
            targets.append(target)

    return targets


def replace_text(path: Path, old: str, new: str) -> None:
    content = path.read_text()
    path.write_text(content.replace(old, new))


def replace_if_changed(source: Path, target: Path) -> bool:
    new_content = source.read_text()
    if target.exists() and target.read_text() == new_content:
        return False
    target.write_text(new_content)
    return True


def prepend_marker(path: Path) -> None:
    content = path.read_text()
    if content.startswith(FONT_MARKER):
        return
    path.write_text(f"{FONT_MARKER}\n{content}")


def lv_font_conv_args(target: dict, out_c: Path) -> list[str]:
    args = []
    args.extend(normalize_list(target.get("args")))
    args.extend(normalize_list(target.get("extra_args")))

    if "size" in target:
        args.extend(["--size", str(target["size"])])
    if "bpp" in target:
        args.extend(["--bpp", str(target["bpp"])])

    args.extend(["--font", str(target["source_path"])])
    if "ranges" in target:
        for font_range in normalize_list(target["ranges"]):
            args.extend(["-r", font_range])
    elif "range" in target:
        for font_range in normalize_list(target["range"]):
            args.extend(["-r", font_range])
    if "symbols" in target:
        args.extend(["--symbols", "".join(normalize_list(target["symbols"]))])

    args.extend([
        "--format", "lvgl",
        "-o", str(out_c),
    ])
    return args


def convert_font(font_conv: str, target: dict, tmp_dir: Path) -> tuple[Path, bool]:
    RES_C_DIR.mkdir(parents=True, exist_ok=True)
    out_c = RES_C_DIR / f"{target['symbol']}.c"
    tmp_c = tmp_dir / f"{target['symbol']}.c"
    cmd = [font_conv, *lv_font_conv_args(target, tmp_c)]

    subprocess.run(cmd, check=True)
    replace_text(tmp_c, str(tmp_c), convert_images.display_path(out_c))
    replace_text(
        tmp_c,
        str(target["source_path"]),
        convert_images.display_path(target["source_path"], ASSETS_DIR),
    )
    prepend_marker(tmp_c)
    changed = replace_if_changed(tmp_c, out_c)
    return out_c, changed


def update_assets_header(fonts_dir: Path) -> bool:
    images = convert_images.iter_images(IMAGES_DIR)
    symbols_by_image = convert_images.image_symbols(images)
    return convert_images.write_assets_header(
        [symbols_by_image[image] for image in images],
        convert_images.font_symbols_from_configs(fonts_dir),
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert font assets to LVGL C fonts.")
    parser.add_argument("--fonts-dir", type=Path, default=FONTS_DIR,
                        help="Input font config directory.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    fonts_dir = args.fonts_dir.resolve()
    targets = font_targets(fonts_dir)
    if not targets:
        print(f"no font targets in {convert_images.display_path(fonts_dir)}")
        return 0

    font_conv = find_lv_font_conv()
    with tempfile.TemporaryDirectory(prefix="assets-fonts-") as tmp:
        tmp_dir = Path(tmp)
        for target in targets:
            out_c, changed = convert_font(font_conv, target, tmp_dir)
            status = "updated" if changed else "unchanged"
            print(
                f"{convert_images.display_path(target['source_path'], fonts_dir)} -> "
                f"{convert_images.display_path(out_c)} ({target['symbol']}, {status})")

    header_changed = update_assets_header(fonts_dir)
    status = "updated" if header_changed else "unchanged"
    print(f"{status} {convert_images.display_path(convert_images.ASSETS_H, convert_images.repo_root())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
